### ISSUE TITLE
Issue when building/serving on windows

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#97]
```bash
C:\Website\git\Gloria\test>gloria serve
Preparing to serve static files from: C:\Website\git\Gloria\test\site
Clearing dest directory C:\Website\git\Gloria\test\site.
starting to walk the file system
ignoring \_config.yml
ignoring \_includes
ignoring \_layout
ignoring \_posts
Copying C:\Website\git\Gloria\test\.npmignore  to C:\Website\git\Gloria\test\site\.npmignore
Copied 21 public files.
file C:\Website\git\Gloria\test\site\blog\index.html written
file C:\Website\git\Gloria\test\site\index.html written
file C:\Website\git\Gloria\test\site\blog\meta\first-post\index.html written
Build time: 117.578ms
# of public files: 21
# of pages: 2
# of posts: 1
# of sass: 0
# of stylus: 0
# of JSON: 0
Watching C:\Website\git\Gloria\test folder, ignoring /C:\Website\git\Gloria\test\site|C:\Website\git\Gloria\test\.git/
Serving static files from C:\Website\git\Gloria\test\site
Never use this in production. See the deployment section
    in the documentation for more information about deployment.
listening in port 3300
file C:\Website\git\Gloria\test\site  changed
Clearing dest directory C:\Website\git\Gloria\test\site.
C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\fs-extra\lib\remove\rimraf.js:266
      throw er
      ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Website\git\Gloria\test\site\blog\meta'
    at Object.fs.rmdirSync (fs.js:818:18)
    at rmkidsSync (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\fs-extra\lib\remove\rimraf.js:300:11)
    at rmdirSync (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\fs-extra\lib\remove\rimraf.js:289:7)
    at rimrafSync (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\fs-extra\lib\remove\rimraf.js:254:7)
    at C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\fs-extra\lib\remove\rimraf.js:298:5
    at Array.forEach (native)
    at rmkidsSync (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\fs-extra\lib\remove\rimraf.js:297:26)
    at rmdirSync (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\fs-extra\lib\remove\rimraf.js:289:7)
    at Function.rimrafSync [as sync] (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\fs-extra\lib\remove\rimraf.js:254:7)
    at Object.removeSync (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\fs-extra\lib\remove\index.js:4:17)
    at C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\fs-extra\lib\empty\index.js:38:12
    at Array.forEach (native)
    at Object.emptyDirSync (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\fs-extra\lib\empty\index.js:36:9)
    at Object.handler (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\lib\commands\build.js:197:12)
    at watch (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\lib\commands\serve.js:45:15)
    at C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\node-watch\lib\watch.js:149:20
    at Array.forEach (native)
    at Object.each (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\node-watch\lib\watch.js:100:20)
    at Timeout._onTimeout (C:\Users\Alexander\AppData\Roaming\npm\node_modules\gloria\node_modules\node-watch\lib\watch.js:144:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by dvidsilva** [comment]
Not fixed still, the problem seems to be related to watching source files and rebuilding. If you run `gloria serve -w=false` it will work, but that's not ideal.
